# Generated by Django 3.0.2 on 2020-02-26 08:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='content',
            field=tinymce.models.HTMLField(default=True),
        ),
    ]
